export const DEFAULT_PPI_SERIES = 'WPUIP2321001';

export const JOB_TEMPLATES = {
  painting: { name: 'Interior Painting', qtyLabel: 'Rooms', directBase: 210, lowBase: 340, medBase: 460, maxBase: 620, options: [{ id: 'trim', label: 'Include trim', pct: .16 }, { id: 'ceiling', label: 'Include ceiling', pct: .20 }, { id: 'coats2', label: 'Two coats (vs. one)', pct: .14 }], prep: [{ id: 'light', label: 'Light prep - minor patching', pct: 0 }, { id: 'medium', label: 'Medium prep - sanding, some patch', pct: .10 }, { id: 'heavy', label: 'Heavy prep - repairs, stripping', pct: .24 }], confidence: 78, sources: [{ name: 'Bureau of Labor Statistics - regional labor rates', tag: 'live' }, { name: 'Craftsman National Cost Data - painting division', tag: 'pending' }, { name: "James's historical job data", tag: 'internal' }] },
  cabinets: { name: 'Cabinet Refinishing', qtyLabel: 'Kitchens', directBase: 1400, lowBase: 2200, medBase: 3100, maxBase: 4400, options: [{ id: 'hardware', label: 'Replace hardware (hinges + pulls)', pct: .09 }, { id: 'interiors', label: 'Paint cabinet interiors', pct: .15 }, { id: 'gloss', label: 'High-gloss / lacquer finish (vs. satin)', pct: .22 }], prep: [{ id: 'low', label: 'Low grease / light cleaning', pct: 0 }, { id: 'medium', label: 'Medium grease - degrease + sand', pct: .12 }, { id: 'heavy', label: 'Heavy grease / kitchen use - full strip', pct: .28 }], confidence: 58, sources: [{ name: 'Bureau of Labor Statistics - general finish labor', tag: 'live' }, { name: 'Craftsman National Cost Data - cabinetry', tag: 'pending' }, { name: '1build API - refinishing line items', tag: 'pending' }, { name: "James's historical job data", tag: 'internal' }] },
  faucet: { name: 'Faucet Replacement', qtyLabel: 'Faucets', directBase: 95, lowBase: 160, medBase: 220, maxBase: 310, options: [{ id: 'valve', label: 'Shut-off valve replacement needed', pct: .28 }, { id: 'drilling', label: 'New hole drilling required', pct: .35 }], prep: [{ id: 'chrome', label: 'Standard chrome / stainless finish', pct: 0 }, { id: 'nickel', label: 'Brushed nickel finish', pct: .06 }, { id: 'bronze', label: 'Oil-rubbed bronze / designer finish', pct: .14 }], confidence: 71, sources: [{ name: 'Bureau of Labor Statistics - plumbing labor', tag: 'live' }, { name: 'Craftsman National Cost Data - fixtures', tag: 'pending' }, { name: "James's historical job data", tag: 'internal' }] },
};
export const CONDITIONS = [{ id: 'normal', label: 'Normal wear', mult: 1 }, { id: 'deferred', label: 'Deferred maintenance', mult: 1.1 }, { id: 'water', label: 'Water damage', mult: 1.15 }, { id: 'fire', label: 'Fire damage', mult: 1.3 }];
export const QUALITY = [{ id: 'builder', label: 'Builder grade', mult: .9 }, { id: 'standard', label: 'Standard', mult: 1 }, { id: 'premium', label: 'Premium', mult: 1.25 }];
export const SCOPE_CATALOG = Object.entries(JOB_TEMPLATES).map(([id, t]) => ({ id, name: t.name, unit: t.qtyLabel, trade: t.name }));
export const DEMO_LABOR_RATE = 40;
export function initTemplateState(template) { return { qty: 1, prep: template.prep[0].id, ...Object.fromEntries(template.options.map(o => [o.id, false])) }; }
export function resolveTemplate(template, state) { const selected = template.options.filter(o => state[o.id]); const prep = template.prep.find(p => p.id === state.prep) || template.prep[0]; const modifierPct = selected.reduce((sum, o) => sum + o.pct, 0) + prep.pct; return { selectedOptions: selected, prep, modifierPct, multiplier: (1 + modifierPct) * Number(state.qty || 1) }; }
export function calculatePricing(template, state, marginPct = 40, bufferPct = 8) { const resolved = resolveTemplate(template, state); const low = template.lowBase * resolved.multiplier, med = template.medBase * resolved.multiplier, max = template.maxBase * resolved.multiplier, direct = template.directBase * resolved.multiplier; const margin = Number(marginPct) / 100; const recommended = direct / (1 - Math.min(.9, Math.max(0, margin))); const percentile = Math.max(0, Math.min(100, ((recommended - low) / Math.max(max - low, 1)) * 100)); const bufferAmt = recommended * Number(bufferPct) / 100; return { ...resolved, low, med, max, direct, recommended, percentile, bufferAmt, total: recommended + bufferAmt, margin, bufferPct: Number(bufferPct) / 100, confidence: template.confidence }; }
export function generateScope(template, state) { const opts = []; if (state.trim) opts.push('trim'); if (state.ceiling) opts.push('ceiling'); if (state.hardware) opts.push('new hinges and pulls'); if (state.interiors) opts.push('cabinet interiors painted'); if (state.valve) opts.push('shut-off valve replacement'); if (state.drilling) opts.push('new hole drilling'); const prep = template.prep.find(p => p.id === state.prep) || template.prep[0]; if (template === JOB_TEMPLATES.painting) return `Interior painting, ${state.qty} room(s). Scope: walls${opts.length ? `, ${opts.join(', ')}` : ''}. ${state.coats2 ? 'Two coats.' : 'One coat.'} ${prep.label.split(' - ')[0]} surface prep. Paint and sundries included; does not include drywall repair beyond standard patching.`; if (template === JOB_TEMPLATES.cabinets) return `Cabinet refinishing, ${state.qty} kitchen(s). Finish: ${state.gloss ? 'high-gloss lacquer' : 'satin'}. ${prep.label.split(' - ')[0]}. ${opts.length ? `Includes ${opts.join(' and ')}.` : 'Doors and drawer fronts only - hardware and interiors not included unless noted.'}`; return `Faucet replacement, ${state.qty} fixture(s). Finish: ${prep.label}. ${opts.length ? `Includes ${opts.join(' and ')}.` : 'Standard swap - existing valve and hole configuration reused.'}`; }
export function clampMarginPct(value) { const n = Number(value); return Number.isFinite(n) ? Math.min(90, Math.max(0, n)) : 0; }
export function validateEstimateInput(input) { const errors = []; if (!String(input.projectName || '').trim()) errors.push('Project name is required.'); if (!/^\d{5}$/.test(String(input.zip || ''))) errors.push('ZIP code must be 5 digits.'); if (Number(input.marginPct) < 0 || Number(input.marginPct) > 90) errors.push('Target margin must be between 0% and 90%.'); return errors; }
